// custom_event.js
// ===============
//
// Created at 2010/05/07
// Copyright (c) 2010-2012 Wolfger Schramm <wolfger@spearwolf.de>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of
// this software and associated documentation files (the "Software"), to deal in
// the Software without restriction, including without limitation the rights to
// use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
// the Software, and to permit persons to whom the Software is furnished to do so,
// subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
// FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
// COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
// IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
(function(){var m,v,q,s;function z(b,d,a,c){var f=w++,b={name:b,eType:d,node:a};d===m&&(b.callback=c.callback);t[f]=b;return f}function j(b,d){this.eType=v;this.name=b;this.parentNode=d;this.children=[];this.greedyChildren=[];this.insatiableChildren=[];this.callbacks=[]}function x(b,d){var a=(d||{}).except||[],c;a instanceof Array||(a=[a]);for(c in b)b.hasOwnProperty(c)&&-1===a.indexOf(c)&&delete b[c]}function u(b,d,a){var a=a||{},c=null;if("string"===typeof b)return a.name=b,c=p.findOrCreateNode(b).addCallback(d,
a),{eType:s,id:c.id,name:c.name,destroy:function(){e.destroy(c.id);x(this)},emit:function(){e.emit.apply(i,[c.name].concat(Array.prototype.slice.call(arguments)))},pause:function(a){return"boolean"===typeof a?c.paused=a:c.paused}};if("function"===typeof b&&b.eType===q)return b.on(d)}function y(b,d){var a=[],c=[],f,g,n,l=b,h=d;(n="object"===typeof l)?"function"===typeof l.collect&&(f=l.collect):(h=b,l={});for(g=n?2:1,n=arguments.length;g<n;++g)!0===l.collect&&g===n-1&&"function"===typeof arguments[g]?
f=arguments[g]:a.push(arguments[g]);o.traceGroup("_e.emit ->",h);var j;"object"!==typeof e._emitStackTrace?e._emitStackTrace={currentLevel:1,topicPath:[]}:++e._emitStackTrace.currentLevel;j=e._emitStackTrace;p.matchNodes(h,function(b,d){try{var f=[],l=function(a){return function(){f.push(a)}},n,i,k,m;for(g=0;g<b.callbacks.length;g++)k=b.callbacks[g],k.paused?o.trace("_e.on -> (paused)",k.name,"["+k.id+"]",k):0>j.topicPath.indexOf(k.id)?(j.topicPath.push(k.id),i=k.binding||{},i.name=h,i.destroy=l(k.id),
"undefined"===typeof i.eType&&(i.eType=s),m=a,"undefined"!==typeof d&&(i.pathArgs=d.split(e.options.pathSeparator),m=i.pathArgs.concat(a)),o.trace("_e.on ->",k.name,"["+k.id+"]",k,"args=",m),n=k.fn.apply(i,m),k.once&&f.push(k.id),null!==n&&"undefined"!==typeof n&&c.push(n),j.topicPath.pop()):o.error("_e.on -> (skipped/recursion)",k.name,"["+k.id+"]",k);b.destroyCallbacks(f)}catch(p){o.error(p)}});--e._emitStackTrace.currentLevel;0===e._emitStackTrace.currentLevel&&(e._emitStackTrace={currentLevel:0,
topicPath:[]});f&&0<c.length&&f.apply(i,c);o.traceGroupEnd()}function r(b,d){var a,d=d||p;if("number"===typeof b)if(a=t[b]){if(a.eType===m){var c=a.node.eValueObject.listener;a=a.callback;var f;for(f=0;f<c.length;f++)if(c[f]===a){c.splice(f,1);break}return!0}delete t[b]}else{if(0<d.destroyCallbacks([b]))return!0;for(c=0;c<d.children.length;c++)if(r(b,d.children[c]))return!0;for(c=0;c<d.greedyChildren.length;c++)if(r(b,d.greedyChildren[c]))return!0;for(c=0;c<d.insatiableChildren.length;c++)if(r(b,
d.insatiableChildren[c]))return!0}return!1}var i=this,e={VERSION:"0.7.0-pre2"};"undefined"!==typeof exports?("undefined"!==typeof module&&module.exports&&(exports=module.exports=e),exports._e=e):"function"===typeof define&&define.amd?(define("custom_event",function(){return e}),define("custom_event/global",function(){return i._e=e})):i._e=e;var o=function(){var b="undefined"!==typeof i.console&&"function"===typeof Function&&"function"===typeof Function.prototype.bind,d=b&&"function"===typeof i.console.group,
a={},c=!b?void 0:function(a){return Function.prototype.bind.call(console[a],console)},f=b?c("error"):null,g=b?c("log"):null,n=b?c("log"):null,l=d?c("group"):null,h="";b?(a.error=function(){f.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.debug=function(){e.options.debug&&g.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.trace=function(){e.options.trace&&n.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},
d?(a.debugGroup=function(){e.options.debug&&l.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.debugGroupEnd=function(){e.options.debug&&console.groupEnd()},a.traceGroup=function(){e.options.trace&&l.apply(console,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments)))},a.traceGroupEnd=function(){e.options.trace&&console.groupEnd()}):(a.debugGroup=function(){e.options.debug&&(g.apply(i,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments))),
h+="    ")},a.traceGroup=function(){e.options.trace&&(n.apply(i,[h+"custom_event.js:"].concat(Array.prototype.slice.call(arguments))),h+="    ")},a.traceGroupEnd=a.debugGroupEnd=function(){h=h.substr(0,h.length-4)})):a.error=a.debug=a.trace=a.traceGroup=a.traceGroupEnd=function(){};return a}();v="EventNode";q="ValueFunction";m="ValueChangeListener";s="EventListener";var w=1,t={},p=new j;j.prototype.fullPathName=function(){return"undefined"===typeof this.name?e.options.pathSeparator:this._fullPathName()};
j.prototype._fullPathName=function(){return"undefined"===typeof this.name?"":this.parentNode._fullPathName()+e.options.pathSeparator+this.name};j.prototype.addChild=function(b){var d=new j(b,this);b===e.options.greedyChar?this.greedyChildren.push(d):b===e.options.insatiableSequence?this.insatiableChildren.push(d):this.children.push(d);return d};j.prototype.splitPath=function(b){for(var b=b.split(e.options.pathSeparator),d=null;null===d||0===d.length;)d=b.shift();if(d===e.options.insatiableSequence)return[d,
""];for(var a=[],c=0;c<b.length&&!(a.push(b[c]),b[c]===e.options.insatiableSequence);c++);return[d,0===a.length?"":a.join(e.options.pathSeparator)]};j.prototype.matchNodes=function(b,d){var a=this.splitPath(b),c=a[0],a=a[1],f=this,g;for(g=0;g<f.insatiableChildren.length;g++)d(f.insatiableChildren[g],b);if(0<a.length){for(g=0;g<this.children.length;g++)f=this.children[g],(c===e.options.greedyChar||c===f.name)&&f.matchNodes(a,d);for(g=0;g<this.greedyChildren.length;g++)this.greedyChildren[g].matchNodes(a,
d)}else{for(g=0;g<this.children.length;g++)f=this.children[g],(c===e.options.greedyChar||c===f.name)&&d(f);for(g=0;g<this.greedyChildren.length;g++)d(this.greedyChildren[g])}};j.prototype.findOrCreateNode=function(b,d){var a=this.splitPath(b),c=a[0],a=a[1],d="undefined"===typeof d?!0:d,f=function(a){return function(b){var c,f;for(c=0;c<a.children.length;c++)if(f=a.children[c],b===f.name)return f;if(d)for(c=0;c<a.greedyChildren.length;c++)if(f=a.greedyChildren[c],b===f.name)return f;return null}}(this)(c);
null===f&&(f=this.addChild(c));return 0<a.length?f.findOrCreateNode(a):f};j.prototype.addCallback=function(b,d){b={eType:"eCallback",id:w++,name:d.name,fn:b,once:!!d.once,binding:d.binding,paused:!1};this.callbacks.push(b);return b};j.prototype.destroyCallbacks=function(b){var d=[],a,c,f,e=0;for(a=0;a<this.callbacks.length;a++){f=!1;for(c=0;c<b.length;c++)if(this.callbacks[a].id==b[c]){f=!0;++e;break}f||d.push(this.callbacks[a])}this.callbacks=d;return e};e.on=u;e.idle=function(b,d,a,c){function f(){l&&
clearTimeout(l);l=void 0}function e(a){a&&(m=a);f();l=setTimeout(i,m)}function i(){l=void 0;h.pause(!0);a.apply(o);o.pause()||(e(),h.pause(!1))}var l,h,j=!1,m=d,o={eType:"IdleEventListener",destroy:function(){f();h.destroy()},pause:function(a,b){if("undefined"===typeof a)return j;(j=a)?(f(),h.pause(!0)):l||(e(b),h.pause(!1))},start:function(a){this.pause(!1,a)},stop:function(){this.pause(!0)},touch:function(){h.emit()}};h=u(b,e,c);e();return o};e.once=function(b,d,a){a=a||{};a.once=!0;return u(b,
d,a)};e.emit=y;e.collect=function(){y.apply(i,[{collect:!0}].concat(Array.prototype.slice.call(arguments)))};e.connect=function(){var b=Array.prototype.slice.call(arguments),d=b.shift();return e.on(d,function(){for(var a=Array.prototype.slice.call(arguments),c=0;c<b.length;++c)if("string"===typeof b[c])e.emit.apply(i,[b[c]].concat(a));else if("function"===typeof b[c]&&b[c].eType===q)b[c](a[0])})};e.destroy=r;e.val=function(b){var d=p.findOrCreateNode(b,!1);"undefined"===typeof d.eValueObject&&(d.eValueObject=
{eType:"ValueObject",name:b,data:void 0,initialized:!1,getterQueue:[],listener:[]},d.eValueFunction=function(a){var b=function(){return 0===arguments.length?d.eValueFunction.get():d.eValueFunction.set(arguments[0])};b.eType=q;b.eValueObject=a;b.set=function(b){a.data=b;if(!a.initialized){for(b=0;b<a.getterQueue.length;b++)try{a.getterQueue[b](a.data)}catch(d){o.error("e_val('"+a.name+"') getter error",d)}delete a.getterQueue;a.initialized=!0}for(b=0;b<a.listener.length;b++)try{a.listener[b](a.data)}catch(c){o.error("e_val('"+
a.name+"') on[change] listener error",c)}return a.data};b.on=function(b){a.listener.push(b);var c=z(a.name,m,d,{callback:b});return{eType:m,id:c,name:a.name,destroy:function(){e.destroy(c);x(this)}}};b.get=function(b){if("function"===typeof b)a.initialized?b(a.data):a.getterQueue.push(b);else return a.data};b.isEqual=function(b){return a.data===b};b.isDefined=function(){return a.initialized};return b}(d.eValueObject));return d.eValueFunction};e.get=function(b,d){e.val(b).get(d)};e.set=function(b,
d){e.val(b).set(d)};e.options={pathSeparator:"/",greedyChar:"*",insatiableSequence:"**",trace:!1,debug:!1};e._rootNode=p;e.log=o})();
